# Generated by Django 4.1 on 2023-06-21 10:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_education.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('semestre', models.IntegerField()),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='concours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='famille_competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='fiche_synthese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='filiere_prepa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigle', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='grandeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('unite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
            options={
                'ordering': ['tp', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='item_synthese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='uploads/images_ressources/')),
                ('couleur', models.CharField(choices=[('text-white bg-primary', 'Primary'), ('text-white bg-secondary', 'Secondary'), ('text-white bg-success', 'Success'), ('text-white bg-danger', 'Danger'), ('text-white bg-warning', 'Warning'), ('bg-light', 'Light'), ('text-white bg-dark', 'Dark')], default='Light', max_length=100)),
                ('reponse', models.CharField(max_length=1000)),
                ('fiche_synthese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.fiche_synthese')),
            ],
            options={
                'ordering': ['fiche_synthese', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='reglage_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('jour', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('competence', models.ManyToManyField(to='django_education.competence')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ressource_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('basthon', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='sequence_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='systeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.FileField(upload_to='systemes/')),
                ('sysml', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='type_de_fichier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=100)),
                ('nom_latex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='type_image_systeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=100)),
                ('nom_latex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cours',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_education.ressource')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
            bases=('django_education.ressource',),
        ),
        migrations.CreateModel(
            name='cours_info',
            fields=[
                ('ressource_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_education.ressource_info')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
            bases=('django_education.ressource_info',),
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('annee', models.CharField(choices=[('PTSI', 'PTSI'), ('PT', 'PT')], default='PTSI', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='khole',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_education.ressource')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
            bases=('django_education.ressource',),
        ),
        migrations.CreateModel(
            name='langue_vivante',
            fields=[
                ('matiere_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_education.matiere')),
                ('langue', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
            bases=('django_education.matiere',),
        ),
        migrations.CreateModel(
            name='td',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_education.ressource')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
            bases=('django_education.ressource',),
        ),
        migrations.CreateModel(
            name='td_info',
            fields=[
                ('ressource_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_education.ressource_info')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
            bases=('django_education.ressource_info',),
        ),
        migrations.CreateModel(
            name='tp',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_education.ressource')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
            bases=('django_education.ressource',),
        ),
        migrations.CreateModel(
            name='tp_info',
            fields=[
                ('ressource_info_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_education.ressource_info')),
            ],
            options={
                'ordering': ['sequence', 'numero'],
            },
            bases=('django_education.ressource_info',),
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('nom_fichier', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('competence', models.ManyToManyField(to='django_education.competence')),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.ressource')),
                ('systeme', models.ManyToManyField(blank=True, to='django_education.systeme')),
            ],
            options={
                'ordering': ['ressource__sequence', 'ressource__numero', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='tp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('ilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.ilot')),
            ],
        ),
        migrations.CreateModel(
            name='sujet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django_education.models.max_value_current_year], verbose_name='year')),
                ('sujet_pt', models.CharField(blank=True, choices=[('SiA', 'SiA'), ('SiB', 'SiB'), ('SiC', 'SiC')], default='', max_length=3, null=True)),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.concours')),
                ('systeme', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_education.systeme')),
            ],
            options={
                'ordering': ['systeme__nom'],
            },
        ),
        migrations.CreateModel(
            name='seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rang', models.IntegerField()),
                ('duree_seance', models.IntegerField()),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.ressource')),
            ],
            options={
                'ordering': ['rang'],
            },
        ),
        migrations.AddField(
            model_name='ressource_info',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.sequence_info'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.sequence'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='systeme',
            field=models.ManyToManyField(blank=True, to='django_education.systeme'),
        ),
        migrations.CreateModel(
            name='parametre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField()),
                ('grandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.grandeur')),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.systeme')),
            ],
        ),
        migrations.CreateModel(
            name='image_systeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_image', models.CharField(max_length=100)),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.systeme')),
                ('type_image_systeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.type_image_systeme')),
            ],
        ),
        migrations.AddField(
            model_name='ilot',
            name='systeme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.systeme'),
        ),
        migrations.CreateModel(
            name='fichier_systeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_fichier', models.CharField(max_length=100)),
                ('systeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.systeme')),
                ('type_de_fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.type_de_fichier')),
            ],
        ),
        migrations.AddField(
            model_name='fiche_synthese',
            name='ressource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.ressource'),
        ),
        migrations.CreateModel(
            name='DS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_ds', models.CharField(choices=[('DS', 'DS'), ('DM', 'DM'), ('DC', 'DC'), ('CB', 'CB')], default='DS', max_length=5)),
                ('numero', models.IntegerField()),
                ('date', models.DateField()),
                ('nb_questions', models.IntegerField(blank=True, null=True)),
                ('nb_parties', models.IntegerField(blank=True, null=True)),
                ('coefficients', models.CharField(blank=True, max_length=1000, null=True)),
                ('ajustement', models.FloatField(blank=True, null=True)),
                ('question_parties', models.CharField(blank=True, max_length=100, null=True)),
                ('points_parties', models.CharField(blank=True, max_length=100, null=True)),
                ('moyenne', models.FloatField(blank=True, null=True)),
                ('ecart_type', models.FloatField(blank=True, null=True)),
                ('sujet_support', models.ManyToManyField(blank=True, to='django_education.sujet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='concours',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.filiere_prepa'),
        ),
        migrations.AddField(
            model_name='competence',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.famille_competence'),
        ),
        migrations.AddField(
            model_name='competence',
            name='parent',
            field=models.ManyToManyField(to='django_education.competence'),
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.ressource')),
            ],
        ),
        migrations.CreateModel(
            name='reponse_item_synthese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.CharField(blank=True, max_length=1000, null=True)),
                ('item_synthese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.item_synthese')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.etudiant')),
            ],
            options={
                'ordering': ['item_synthese'],
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('annee', models.CharField(choices=[('PTSI', 'PTSI'), ('PTSI/PT', 'PTSI/PT'), ('PT', 'PT')], default='PTSI', max_length=7)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_education.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='note_suivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(max_length=1000)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.competence')),
                ('ds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.ds')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='ilot',
            name='tp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.tp'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='lv1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_education.langue_vivante'),
        ),
    ]
