# Generated by Django 4.1 on 2023-06-23 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='promotion',
            field=models.IntegerField(blank=True, default=datetime.date),
            preserve_default=False,
        ),
    ]
