# Generated by Django 4.1 on 2023-10-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0002_etudiant_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ressource',
        ),
        migrations.AddField(
            model_name='application',
            name='sequence',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='django_education.sequence'),
            preserve_default=False,
        ),
    ]
