# Generated by Django 3.2.16 on 2023-10-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0002_etudiant_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='parent',
            field=models.ManyToManyField(related_name='_django_education_competence_parent_+', to='django_education.competence'),
        ),
    ]
