# Generated by Django 4.1 on 2023-12-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0003_alter_competence_parent'),
        ('django_education', '0003_remove_application_ressource_application_sequence'),
    ]

    operations = [
    ]
