# Generated by Django 4.1 on 2023-12-05 13:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0004_merge_20231205_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='parent',
            field=models.ManyToManyField(to='django_education.competence'),
        ),
        migrations.CreateModel(
            name='AutoEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.competence')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.etudiant')),
            ],
        ),
    ]
