# Generated by Django 4.1 on 2023-12-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0005_alter_competence_parent_autoevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
