# Generated by Django 3.2 on 2025-03-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0006_alter_ressource_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['sequence', 'numero']},
        ),
        migrations.AlterField(
            model_name='competence',
            name='parent',
            field=models.ManyToManyField(related_name='_django_education_competence_parent_+', to='django_education.competence'),
        ),
        migrations.CreateModel(
            name='video_youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.ressource')),
                ('systeme', models.ManyToManyField(blank=True, to='django_education.systeme')),
            ],
            options={
                'ordering': ['ressource__sequence', 'ressource__numero', 'numero'],
            },
        ),
    ]
