# Generated by Django 3.2 on 2025-03-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0007_auto_20250304_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video_youtube',
            options={'ordering': ['sequence', 'numero']},
        ),
        migrations.RemoveField(
            model_name='video_youtube',
            name='ressource',
        ),
        migrations.AddField(
            model_name='video_youtube',
            name='competence',
            field=models.ManyToManyField(to='django_education.competence'),
        ),
        migrations.AddField(
            model_name='video_youtube',
            name='sequence',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='django_education.sequence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video_youtube',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
