# Generated by Django 3.2 on 2025-03-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0008_auto_20250304_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='video_youtube',
            new_name='videoyoutube',
        ),
    ]
