# Generated by Django 4.1 on 2023-06-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_education', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve', models.ManyToManyField(blank=True, to='django_education.etudiant', verbose_name='Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(help_text='numero de la question', verbose_name='Numero')),
                ('order_item', models.IntegerField(help_text='numéro de classement', verbose_name='Ordre')),
                ('figure', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Figure')),
                ('texte', models.CharField(help_text='Enter the question text', max_length=1000, verbose_name='Question')),
                ('explication', models.TextField(blank=True, help_text='Explanation to be shown ', max_length=2000, verbose_name='Explanation')),
            ],
            options={
                'ordering': ['order_item'],
            },
        ),
        migrations.CreateModel(
            name='Question_QCM_Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the answer text', max_length=1000, verbose_name='Content')),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct answer?', verbose_name='Correct')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text='Description du questionnaire', verbose_name='Description')),
                ('url', models.SlugField(help_text='a user friendly url', max_length=60, verbose_name='user friendly url')),
                ('competences', models.ManyToManyField(blank=True, to='django_education.competence', verbose_name='Competences')),
                ('ressources', models.ManyToManyField(blank=True, to='django_education.ressource', verbose_name='Ressources')),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_education.sequence', verbose_name='Sequence')),
                ('systeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_education.systeme', verbose_name='Systeme')),
            ],
        ),
        migrations.CreateModel(
            name='Status_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Non validé', 'NONVALID'), ('Problème signalé', 'PROBLEM'), ('Validé', 'VALID')], default='NONVALID', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.etudiant', verbose_name='Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Status_Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Non validé', 'NONVALID'), ('Validé', 'VALID')], default='NONVALID', max_length=20)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_education.professeur', verbose_name='Professeur')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.job', verbose_name='Activité')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.quiz', verbose_name='Question')),
                ('status_prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.status_teacher', verbose_name='Status Prof')),
                ('statut_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.status_student', verbose_name='Status Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Question_QCM',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_questionnaire.question')),
            ],
            bases=('django_questionnaire.question',),
        ),
        migrations.CreateModel(
            name='Question_Texte',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_questionnaire.question')),
            ],
            bases=('django_questionnaire.question',),
        ),
        migrations.CreateModel(
            name='Work_QCM',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_questionnaire.work')),
            ],
            bases=('django_questionnaire.work',),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.quiz', verbose_name='Questionnaire'),
        ),
        migrations.AddField(
            model_name='job',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.quiz', verbose_name='Questionnaire'),
        ),
        migrations.CreateModel(
            name='Work_QCM_Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False, help_text="Réponse de l'élève", verbose_name='Réponse')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.question_qcm_proposition', verbose_name='Proposition')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.work_qcm', verbose_name='Travail')),
            ],
        ),
        migrations.AddField(
            model_name='question_qcm_proposition',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.question_qcm', verbose_name='Question'),
        ),
    ]
