# Generated by Django 4.1 on 2023-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_student',
            name='status',
            field=models.CharField(choices=[('NONVALID', 'Non validé'), ('PROBLEM', 'Problème signalé'), ('VALID', 'Validé')], default='NONVALID', max_length=20),
        ),
    ]
