# Generated by Django 4.1 on 2023-06-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0002_alter_status_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_teacher',
            name='status',
            field=models.CharField(choices=[('NONVALID', 'Non validé'), ('VALID', 'Validé')], default='NONVALID', max_length=20),
        ),
    ]
