# Generated by Django 4.1 on 2023-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0003_alter_status_teacher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_student',
            name='status',
            field=models.CharField(choices=[('NVALI', 'NVAL'), ('PROBL', 'PROB'), ('VALID', 'VAL')], default='NVALI', max_length=5),
        ),
        migrations.AlterField(
            model_name='status_teacher',
            name='status',
            field=models.CharField(choices=[('NVALI', 'NVAL'), ('VALID', 'VAL')], default='NVALI', max_length=5),
        ),
    ]
