# Generated by Django 4.1 on 2023-06-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0004_alter_status_student_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_student',
            name='status',
            field=models.CharField(choices=[('PTSI', 'PTSI'), ('PT', 'PT')], default='PTSI', max_length=4),
        ),
        migrations.AlterField(
            model_name='status_teacher',
            name='status',
            field=models.CharField(choices=[('PTSI', 'PTSI'), ('PT', 'PT')], default='PTSI', max_length=4),
        ),
    ]
