# Generated by Django 4.1 on 2023-06-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0001_initial'),
        ('django_questionnaire', '0006_remove_status_teacher_id_alter_status_teacher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_teacher',
            name='prof',
        ),
        migrations.RemoveField(
            model_name='work',
            name='statut_eleve',
        ),
        migrations.AddField(
            model_name='work',
            name='eleve',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='django_education.etudiant', verbose_name='Eleve'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='prof',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='django_education.professeur', verbose_name='Prof'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='status_eleve',
            field=models.CharField(choices=[('NVALI', 'NVAL'), ('VALID', 'VAL')], default='NVALI', max_length=5),
        ),
        migrations.AlterField(
            model_name='work',
            name='status_prof',
            field=models.CharField(choices=[('NVALI', 'NVAL'), ('VALID', 'VAL')], default='NVALI', max_length=5),
        ),
        migrations.DeleteModel(
            name='Status_Student',
        ),
        migrations.DeleteModel(
            name='Status_Teacher',
        ),
    ]
