# Generated by Django 4.1 on 2023-06-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0007_remove_status_teacher_prof_remove_work_statut_eleve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='question',
            new_name='question2',
        ),
    ]
