# Generated by Django 4.1 on 2023-06-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0008_rename_question_work_question2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='question2',
            new_name='question',
        ),
    ]
