# Generated by Django 4.1 on 2023-06-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0009_rename_question2_work_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='question',
            new_name='question2',
        ),
    ]
