# Generated by Django 4.1 on 2023-06-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0011_rename_question2_work_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_qcm',
            name='work_ptr',
        ),
        migrations.RemoveField(
            model_name='work_qcm_proposition',
            name='proposition',
        ),
        migrations.RemoveField(
            model_name='work_qcm_proposition',
            name='work',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='Work_QCM',
        ),
        migrations.DeleteModel(
            name='Work_QCM_Proposition',
        ),
    ]
