# Generated by Django 4.1 on 2023-06-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0001_initial'),
        ('django_questionnaire', '0012_remove_work_qcm_work_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_eleve', models.CharField(choices=[('NVALI', 'NVAL'), ('VALID', 'VAL')], default='NVALI', max_length=5)),
                ('status_prof', models.CharField(choices=[('NVALI', 'NVAL'), ('VALID', 'VAL')], default='NVALI', max_length=5)),
                ('eleve', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_education.etudiant', verbose_name='Eleve')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.job', verbose_name='Activité')),
                ('prof', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='django_education.professeur', verbose_name='Prof')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.quiz', verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='Work_QCM',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_questionnaire.work')),
            ],
            bases=('django_questionnaire.work',),
        ),
        migrations.CreateModel(
            name='Work_QCM_Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False, help_text="Réponse de l'élève", verbose_name='Réponse')),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.question_qcm_proposition', verbose_name='Proposition')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.work_qcm', verbose_name='Travail')),
            ],
        ),
    ]
