# Generated by Django 4.1 on 2023-06-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_education', '0001_initial'),
        ('django_questionnaire', '0013_work_work_qcm_work_qcm_proposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='eleve',
            field=models.ManyToManyField(to='django_education.etudiant', verbose_name='Etudiant'),
        ),
        migrations.AlterField(
            model_name='work',
            name='eleve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_education.etudiant', verbose_name='Eleve'),
        ),
        migrations.AlterField(
            model_name='work',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_education.professeur', verbose_name='Prof'),
        ),
        migrations.AlterField(
            model_name='work',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_questionnaire.question', verbose_name='Question'),
        ),
    ]
