# Generated by Django 4.1 on 2023-06-22 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0014_alter_job_eleve_alter_work_eleve_alter_work_prof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_qcm',
            name='work_ptr',
        ),
        migrations.AddField(
            model_name='work_qcm',
            name='Work',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='thissubclass', serialize=False, to='django_questionnaire.work'),
            preserve_default=False,
        ),
    ]
