# Generated by Django 4.1 on 2023-06-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0015_remove_work_qcm_work_ptr_work_qcm_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_qcm',
            name='work_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_questionnaire.work'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work_qcm',
            name='Work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thissubclass', to='django_questionnaire.work'),
        ),
    ]
