# Generated by Django 4.1 on 2023-06-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0018_work_work_qcm_work_qcm_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='datetime',
            field=models.DateTimeField(default='2023-06-30 18:12:48'),
            preserve_default=False,
        ),
    ]
