# Generated by Django 4.1 on 2023-06-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0019_job_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question_Picture',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_questionnaire.question')),
            ],
            bases=('django_questionnaire.question',),
        ),
        migrations.CreateModel(
            name='Work_Picture',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_questionnaire.work')),
                ('image', models.ImageField(height_field=500, upload_to='travail_eleve')),
                ('commentaire', models.TextField(blank=True, help_text='Commentaire', verbose_name='Commentaire')),
            ],
            bases=('django_questionnaire.work',),
        ),
    ]
