# Generated by Django 4.1 on 2023-06-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0020_question_picture_work_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_qcm',
            name='work',
        ),
        migrations.AddField(
            model_name='work_qcm',
            name='work_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_questionnaire.work'),
            preserve_default=False,
        ),
    ]
