# Generated by Django 4.1 on 2023-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0021_remove_work_qcm_work_work_qcm_work_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_picture',
            name='image',
            field=models.ImageField(height_field=500, upload_to='uploads/travail_eleve'),
        ),
    ]
