# Generated by Django 4.1 on 2023-06-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0022_alter_work_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_picture',
            name='image',
            field=models.FileField(upload_to='uploads/travail_eleve'),
        ),
    ]
