# Generated by Django 4.1 on 2023-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0023_alter_work_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_picture',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/travail_eleve'),
        ),
    ]
