# Generated by Django 4.1 on 2023-06-27 13:48

from django.db import migrations, models
import django_questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0024_alter_work_picture_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['num']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_item',
        ),
        migrations.AlterField(
            model_name='work_picture',
            name='commentaire',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='work_picture',
            name='image',
            field=models.FileField(blank=True, upload_to=django_questionnaire.models.work_picture_url),
        ),
    ]
