# Generated by Django 4.1 on 2023-06-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0025_alter_question_options_remove_question_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='status_eleve',
            field=models.CharField(choices=[('NVALI', 'Non validé'), ('BASSI', "Besoin d'assistance"), ('VALID', 'Validé')], default='NVALI', max_length=10),
        ),
        migrations.AlterField(
            model_name='work',
            name='status_prof',
            field=models.CharField(choices=[('NVALI', 'NVAL'), ('VALID', 'VAL')], default='NVALI', max_length=10),
        ),
    ]
