# Generated by Django 4.1 on 2023-06-29 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_questionnaire', '0026_alter_job_datetime_alter_work_status_eleve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='eleve',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Etudiant'),
        ),
        migrations.AlterField(
            model_name='work',
            name='status_prof',
            field=models.CharField(choices=[('NVALI', 'Non validé'), ('VALID', 'Validé')], default='NVALI', max_length=10),
        ),
    ]
