# Generated by Django 4.1 on 2023-06-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0027_remove_job_eleve_job_user_alter_work_status_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
