# Generated by Django 4.1 on 2023-09-07 13:30

from django.db import migrations, models
import django_questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0029_alter_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='texte',
            field=models.TextField(help_text='Enter the question text', max_length=1000, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='work_picture',
            name='image',
            field=models.ImageField(blank=True, upload_to=django_questionnaire.models.work_picture_url),
        ),
        migrations.DeleteModel(
            name='Question_Texte',
        ),
    ]
