# Generated by Django 4.1 on 2023-09-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_questionnaire', '0030_alter_question_texte_alter_work_picture_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz', 'num']},
        ),
    ]
